
-- FRESH FAKE DATA GENERATION
BEGIN;

-- 0. USERS (For Auth)
-- Default admin is usually created manually, but we ensure doctors have logins
INSERT INTO users (username, password, role) VALUES ('admin', 'admin123', 'admin');
INSERT INTO users (username, password, role) VALUES ('dr.smith', 'pass123', 'doctor'); -- Links to Doctor ID 1 potentially depending on logic


-- 1. PATIENTS 
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Robert', 'Smith', '1975-08-27', 'Other', '(434)796-2516x4', '698 Eddie Stravenue, East Marymouth, AK 60641', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Matthew', 'Ponce', '1991-07-22', 'Female', '4028924161', '31738 Jonathan Mews Apt. 024, East Tammiestad, ND 45323', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Eric', 'Morris', '1941-09-20', 'Other', '3719620538', '759 Livingston Plaza, West Kayla, UT 16148', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Angela', 'Miller', '1957-06-16', 'Female', '433-322-4281x80', '76232 Nathan Fall Suite 229, South William, MT 43094', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('David', 'Schneider', '1961-07-22', 'Female', '+1-299-632-8359', '8891 Eric Station, West Juliestad, MO 40773', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Shane', 'Baker', '2002-01-14', 'Male', '504.870.3520x10', '3456 Christina Land Apt. 632, East Lisabury, MA 56113', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('James', 'Hernandez', '2004-12-17', 'Female', '5566503172', '40118 Andrea Shoals Suite 808, New Amanda, OR 21958', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Stephen', 'Gonzales', '1985-08-08', 'Male', '+1-606-458-9057', '171 Christina Bypass, West Maryhaven, CT 60852', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Victor', 'Brown', '1964-12-15', 'Female', '552.569.8372', '31181 Joseph Freeway Apt. 437, Jessicamouth, TN 53394', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Anna', 'Curtis', '2003-08-30', 'Female', '380-888-5367', '74691 Jeffery Ridges Suite 492, New Jessicaview, AK 63325', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Rachel', 'Benson', '1962-06-13', 'Other', '+1-240-265-3843', '3299 Dixon Burgs, South Phillip, TX 76659', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Richard', 'Lucas', '2024-11-25', 'Male', '298.348.4817x72', '5667 Tina Spurs, Lake Ryantown, WV 60643', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Eric', 'Smith', '1956-10-19', 'Male', '+1-942-262-4595', '2959 Hogan Curve Suite 707, Jerryfort, IN 81334', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('William', 'Vasquez', '2016-01-05', 'Other', '865.412.2801', '301 Green Gateway, Stacyshire, ME 45945', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Leslie', 'Smith', '1951-06-26', 'Other', '001-277-453-412', '434 Williams Squares, Port Joyce, VT 06350', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Lindsey', 'Taylor', '1939-11-17', 'Female', '(466)996-0228', '120 Lindsay Knoll Apt. 553, Jamesmouth, MO 09772', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Martin', 'King', '2010-02-28', 'Female', '(482)660-7242', 'USNV Roberts, FPO AE 68335', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Anne', 'Dawson', '2010-04-14', 'Other', '361.318.2782', '07164 Anderson Pike Apt. 216, West John, DE 88478', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Lee', 'Foster', '2015-02-26', 'Other', '335-964-0496x76', '2833 Rebecca Underpass, East David, SD 01111', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Maria', 'Garcia', '1936-12-18', 'Other', '001-204-818-407', '16275 Singh Divide Suite 362, Jenningsstad, VT 30023', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Peter', 'Smith', '1981-10-22', 'Female', '275-319-4183', 'Unit 5872 Box 3460, DPO AE 16447', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('George', 'Hall', '1949-11-02', 'Male', '860.839.7685', '21570 Mack Mountain Apt. 876, North Christopher, AS 20773', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Scott', 'Herring', '1994-09-01', 'Other', '6567556887', '77981 Adams Island, Reedside, WY 41113', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Hannah', 'Schmidt', '1959-10-12', 'Male', '711-876-7793x63', '57030 Nathaniel Walk, East Lisaport, TX 52447', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Victoria', 'Lucas', '1962-05-02', 'Male', '001-555-956-337', '722 Black Knoll, West Anthony, GA 18084', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Monica', 'Hampton', '1951-05-17', 'Other', '396-495-8536x16', '14253 Walton Greens Suite 750, Michellehaven, TN 74038', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Anthony', 'Diaz', '1968-01-28', 'Female', '2192235477', '915 Brittany Unions, Zacharytown, OR 14653', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Angela', 'Harris', '1976-02-04', 'Other', '(726)493-7526', '6743 Miller Gateway, Foleyburgh, ND 76831', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Danielle', 'Smith', '1981-03-15', 'Female', '001-247-205-647', '22468 Shawn Ramp Apt. 561, Jonesville, PR 92990', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Angela', 'Frederick', '1957-04-04', 'Female', '303-238-9391x62', '40345 Joseph Road Apt. 768, Smithville, CA 69425', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Annette', 'Davis', '1988-12-14', 'Other', '001-741-256-195', 'Unit 3681 Box 5845, DPO AP 39800', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Alan', 'Shaffer', '1941-09-05', 'Female', '(842)691-1384x6', '13203 Deanna Trace, Diamondland, IA 03219', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Kimberly', 'Howard', '1945-09-09', 'Female', '634.987.3613x67', '496 Peters Roads Apt. 051, Lindsayhaven, KY 85773', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Derrick', 'Shepherd', '1993-06-14', 'Female', '841.664.4608x88', '25153 Robert Divide, Kristinmouth, PW 83675', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Caroline', 'Horn', '1945-03-30', 'Female', '907.471.2493x84', '02920 Joy Passage Apt. 595, North Christianport, MS 17830', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Scott', 'Atkins', '1993-01-30', 'Female', '272-621-6865x66', '26662 Victoria Cape Suite 867, Harrishaven, WY 35460', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Tiffany', 'Cruz', '2020-05-07', 'Female', '+1-741-461-5918', '4369 Sara Heights, Annaborough, ME 72771', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Terry', 'Rivera', '2010-07-14', 'Male', '001-653-888-060', '1763 Gerald Canyon Apt. 576, Lake Brendanland, MH 78089', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Lindsey', 'Mills', '1973-09-09', 'Female', '880.327.0199x13', '1503 David Passage Suite 620, New Anntown, NV 41691', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Nicole', 'Blankenship', '1977-08-07', 'Other', '001-692-507-460', '62175 Harrison River, Krausestad, FL 11249', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('John', 'Navarro', '1973-01-30', 'Male', '(202)234-8627x5', '0640 Stephanie Radial Apt. 996, Saratown, ME 06584', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Jason', 'Lee', '1977-03-15', 'Male', '+1-837-408-6282', 'PSC 3389, Box 0636, APO AE 29106', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Carlos', 'Carson', '2013-11-16', 'Male', '752-639-3774x75', '7371 Marvin Village, Port Danielle, ID 55564', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Valerie', 'Campbell', '1953-07-21', 'Other', '(626)947-1468x6', 'USS Elliott, FPO AP 08545', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Christopher', 'Cox', '1946-12-12', 'Male', '001-651-769-201', '58364 Lopez Summit, New Brandon, MA 78445', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Tiffany', 'Carpenter', '1996-07-11', 'Female', '(742)226-9574x1', '3013 Spencer Lock Suite 158, East Josephmouth, WI 64250', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Dustin', 'Ramirez', '2014-03-10', 'Female', '(304)691-4177x3', 'Unit 4350 Box 4814, DPO AA 97851', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Timothy', 'Smith', '1998-11-22', 'Female', '510.847.0801x76', '784 Zachary Mission, North Michaelberg, VA 83415', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Debra', 'Harper', '1971-08-23', 'Male', '001-282-814-718', '81356 Lyons Court Suite 718, Wilsonchester, IA 08670', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Tracy', 'Lane', '2012-01-18', 'Other', '001-837-715-710', '2549 Hernandez Camp, Ryanfort, CA 41594', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Dennis', 'Stewart', '2005-08-12', 'Female', '734.521.9508x70', '918 Zachary Plains, South Brettland, ID 65306', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Steven', 'Leach', '1971-06-22', 'Female', '7715840146', '7359 Emily Avenue, West Amy, KY 48356', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Renee', 'Peters', '1977-11-10', 'Other', '574.565.9009x87', '1266 George Shoal Suite 264, Lake Melissaville, AZ 59792', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Olivia', 'Wolfe', '1977-09-10', 'Male', '001-760-456-625', '74904 Tommy Place, Jacobsonport, CT 08035', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Lauren', 'Garcia', '2003-04-01', 'Other', '490-459-6763', '439 Bryan Drive Suite 002, Carolside, CA 01680', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Derrick', 'Turner', '1949-01-20', 'Other', '(314)214-0014x6', '444 Jeremy Trace Suite 897, Jacobton, MA 40352', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('James', 'Jones', '1998-06-02', 'Female', '788-456-0675', '550 Shaun Pines Apt. 724, Lake Samuel, MO 76987', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Kathy', 'Cannon', '1945-11-09', 'Other', '+1-382-397-4514', '7125 Bell Place Suite 770, West Donald, PA 13498', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Anthony', 'Wright', '1947-08-27', 'Male', '330-931-3329x87', '0928 Christine Village Suite 277, East Morgan, LA 33825', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Daniel', 'Gomez', '1949-11-20', 'Female', '7574404414', '368 Lauren Light Suite 018, Michaelborough, AK 35750', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Kathleen', 'Frazier', '2010-06-28', 'Female', '5987784619', 'USNS Benjamin, FPO AP 74808', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Dennis', 'Hernandez', '1947-01-26', 'Female', '907-511-4000', '82727 Rice Union, Crystalport, HI 34523', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Randall', 'Casey', '1945-11-03', 'Male', '999-897-6378', 'USCGC Hunter, FPO AE 14300', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('William', 'Marshall', '2004-01-25', 'Female', '+1-302-557-0609', '76996 Thomas Lights, Hammondside, ND 28901', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Xavier', 'Benitez', '2021-09-13', 'Male', '(983)791-1310x0', '720 Gary Hills, Port Angelaland, OK 75696', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Olivia', 'Lewis', '1943-12-14', 'Male', '3957032867', '974 Timothy Shore Apt. 785, North Nicoleland, PW 84041', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Tina', 'Williams', '1996-08-04', 'Male', '4378649089', '307 Davis Motorway Suite 923, Courtneyfurt, OH 90540', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Sherri', 'Solomon', '1947-08-25', 'Male', '696.600.7564x34', '021 Thomas Turnpike Suite 990, Sydneystad, AL 45000', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('John', 'Black', '1994-10-12', 'Male', '6854991239', 'USNV Davis, FPO AA 53758', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Holly', 'Hernandez', '1938-10-23', 'Other', '245-715-2364x74', 'PSC 8734, Box 3568, APO AA 90245', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Robert', 'Fox', '1950-06-02', 'Other', '001-257-617-125', '1040 Parker Street Suite 631, Ericside, WY 08701', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Kelsey', 'Carter', '2017-12-02', 'Male', '863-413-1827', '1243 Michael Street Apt. 881, Danielport, AR 62430', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Kevin', 'Smith', '1951-08-10', 'Female', '001-288-876-091', '05327 Jackson Island Apt. 141, North Erinside, WV 76161', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Miranda', 'Mcdonald', '2023-01-22', 'Male', '(899)972-5885', '89646 Jacqueline Ranch Suite 154, Elizabethberg, NH 96795', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Jennifer', 'Arroyo', '1946-05-04', 'Male', '913.245.6913', '197 Peggy Lakes, Lopezton, TX 56122', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Jeremy', 'Graves', '1944-06-19', 'Other', '(409)654-9484x0', '998 Jon Extensions Suite 885, Port Christopher, FL 13730', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Patricia', 'Martin', '2016-07-17', 'Other', '552.853.1180', '699 Bryan Plaza Apt. 831, South Samuel, MH 51944', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Jenna', 'Murphy', '1979-10-16', 'Female', '001-241-797-424', '6692 Jamie Isle, Erikaville, WI 72045', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Kyle', 'Monroe', '1982-10-01', 'Male', '+1-257-783-2325', 'Unit 9100 Box 2495, DPO AA 53766', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Gerald', 'Carlson', '2023-07-30', 'Male', '+1-307-499-4015', '610 John Flats Suite 549, New Christineberg, VT 58039', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Steven', 'Thompson', '2008-12-26', 'Female', '(964)360-4526x8', '61513 Cory Vista, New Johnton, OK 73235', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Tamara', 'Walker', '2003-11-19', 'Other', '518-485-6148x64', '407 Theresa Trace Apt. 397, Lake Melaniefurt, GU 17018', 'Cigna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Cynthia', 'Saunders', '1955-10-08', 'Female', '(729)400-7597', 'PSC 3704, Box 0605, APO AP 46759', 'None');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Linda', 'Mcpherson', '1951-11-20', 'Other', '+1-249-713-8213', '3772 Berger Village, Petersonview, CO 18305', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Nicole', 'Thomas', '1996-04-02', 'Male', '404-381-3948x55', '70075 Roberts Dam, Sonialand, NY 19723', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('James', 'Warren', '2002-10-14', 'Female', '001-520-294-683', '4666 Victoria Points Suite 986, West Jason, CA 97201', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Joshua', 'Deleon', '2005-04-19', 'Other', '(537)825-4049', '03066 Moore Square Apt. 024, Port Joan, WY 62141', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Kelly', 'Welch', '1954-10-30', 'Male', '001-357-919-904', '0354 Hansen Plain, Kaylafort, IA 24585', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Destiny', 'Johnson', '2018-09-06', 'Male', '001-409-737-866', '74353 Bailey Spring, East Latasha, GA 26786', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('James', 'Hawkins', '1974-12-15', 'Other', '9926941149', 'PSC 6284, Box 7293, APO AA 87706', 'ICICI Lombard');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Ryan', 'Williams', '1949-01-30', 'Female', '+1-680-857-6587', '0093 Gentry Oval Suite 063, Lake Markchester, NM 27948', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Evelyn', 'Bruce', '1935-07-22', 'Other', '(878)212-8892', 'PSC 8218, Box 8779, APO AA 92548', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Shane', 'Kirk', '1984-05-07', 'Other', '738-560-0827', '56962 Moreno Court, Leslieberg, OR 82546', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('John', 'Wallace', '1968-01-01', 'Male', '+1-339-547-5170', '010 Faith Mews, Angelamouth, KY 44574', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Sharon', 'Jacobs', '1951-06-12', 'Female', '+1-828-633-6049', '195 Andrea Junction, East Jasonland, AL 81400', 'Blue Cross');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Thomas', 'Lewis', '1965-05-03', 'Female', '813-364-4350x67', '825 Matthew Manor Apt. 289, Paulville, ME 06650', 'United Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Michael', 'Santos', '1955-06-11', 'Female', '848.881.1617', '738 Carey Streets Apt. 253, Mistymouth, WA 23904', 'Aetna');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Alexander', 'Mcgee', '1954-04-24', 'Male', '927.859.7406x92', '162 Michael Brook Apt. 852, North Juan, NE 57988', 'Medicare');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('Christina', 'Adams', '1985-10-09', 'Other', '386-662-0333x70', '8504 Hall Oval, Weavertown, MH 20036', 'Star Health');
INSERT INTO patients (first_name, last_name, dob, gender, contact_number, address, insurance_provider) VALUES ('William', 'Hernandez', '1987-10-11', 'Male', '869.940.1510x79', '7663 Wise Alley Apt. 354, Ronaldshire, MH 98713', 'Cigna');

-- 2. APPOINTMENTS 
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (83, 19, '2025-11-12 03:49:13', 'R-571', 'Different rise several knowledge be bit quickly.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (32, 9, '2025-07-21 05:52:01', 'R-221', 'Attorney book rest quickly cup feeling man.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (43, 5, '2025-03-29 07:03:02', 'R-459', 'Physical than race plant also.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (36, 3, '2025-08-13 06:38:50', 'R-199', 'Serve effect hear home green.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (48, 18, '2025-11-20 13:01:32', 'R-165', 'Then anything product hear within keep.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (84, 1, '2025-10-24 22:03:54', 'R-195', 'Human tell me range enough contain old.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (18, 8, '2025-06-06 05:50:03', 'R-584', 'Cost himself image season receive source.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (99, 13, '2025-05-26 11:34:59', 'R-276', 'Trip some food leg eight thing.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (9, 10, '2025-10-09 05:29:09', 'R-214', 'Night course now old.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (55, 11, '2025-12-20 05:13:53', 'R-450', 'Case go ever.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (51, 1, '2025-05-29 22:30:28', 'R-439', 'Understand reduce walk wall.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (10, 6, '2025-08-04 05:19:48', 'R-212', 'Field many imagine information.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (33, 18, '2025-03-10 22:17:34', 'R-472', 'Blue general movement dinner Democrat so million throughout.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (20, 20, '2026-01-31 07:35:24', 'R-448', 'Customer free mind city science per hair.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (30, 15, '2025-09-18 02:02:58', 'R-537', 'Continue bank spring need.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (88, 14, '2025-07-06 12:52:24', 'R-588', 'Kid time situation seat this student effort.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (79, 19, '2025-12-02 04:58:07', 'R-220', 'Focus same receive everybody factor west find property.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (76, 6, '2026-01-23 13:21:32', 'R-460', 'Others agreement director.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (12, 19, '2025-10-25 17:04:54', 'R-452', 'Process live responsibility.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (31, 13, '2025-10-15 22:30:34', 'R-506', 'Player line show include here rather.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (38, 15, '2025-03-19 04:36:34', 'R-495', 'Face story order performance commercial local.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (12, 7, '2025-09-12 19:34:27', 'R-179', 'Former rich board free cup.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (18, 18, '2025-02-20 10:21:36', 'R-480', 'Opportunity start machine data middle trial.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (20, 13, '2025-10-16 02:17:12', 'R-360', 'Onto tonight population right.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (65, 3, '2025-04-02 18:11:42', 'R-268', 'Once theory senior whatever eight team coach.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (61, 16, '2025-01-14 18:18:21', 'R-218', 'Although debate different six meeting them gun.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (43, 12, '2025-04-30 20:39:27', 'R-512', 'Explain court shoulder voice nation need.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (35, 4, '2025-10-15 21:04:20', 'R-585', 'Story stay knowledge maybe let clear.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (96, 10, '2025-03-02 23:58:42', 'R-494', 'State kid common American.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (21, 15, '2025-01-23 02:37:42', 'R-389', 'Involve number true serve idea.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (4, 16, '2026-01-13 17:15:54', 'R-400', 'Task exist fear.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (37, 3, '2025-11-11 16:40:01', 'R-237', 'Find garden send experience again house.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (42, 6, '2025-02-23 20:11:42', 'R-114', 'Local president determine move.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (1, 15, '2025-02-04 22:06:49', 'R-140', 'Positive own popular American nation guy discover.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (6, 10, '2025-12-15 17:41:57', 'R-181', 'Recognize we until evidence however which environment.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (63, 3, '2025-04-26 07:22:38', 'R-107', 'Major Mr their.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (66, 3, '2025-07-06 03:22:05', 'R-131', 'Forget street clear fine fly.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (45, 7, '2025-08-31 22:15:42', 'R-424', 'Again once way plan.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (55, 15, '2025-08-06 04:36:01', 'R-114', 'First month toward evidence skill.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (53, 7, '2025-07-23 19:21:24', 'R-599', 'End view political vote such.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (28, 5, '2025-03-13 14:34:56', 'R-129', 'Forward movement thus on somebody whose.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (35, 6, '2025-08-15 02:42:43', 'R-553', 'Enter them defense president window.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (22, 11, '2025-05-10 14:45:29', 'R-381', 'Someone themselves return American manager interview one.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (93, 15, '2025-06-10 12:15:41', 'R-249', 'Finally what other prepare tonight while information history.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (94, 7, '2025-06-09 10:04:57', 'R-199', 'Wind choose figure house coach computer team.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (42, 5, '2026-01-27 22:19:57', 'R-288', 'Magazine public nearly imagine ready study.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (79, 18, '2025-08-26 06:21:06', 'R-438', 'Citizen particularly score reach.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (5, 17, '2025-08-07 02:20:20', 'R-268', 'Small cost figure design.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (74, 19, '2025-12-03 21:34:25', 'R-483', 'Likely sport memory help today.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (20, 3, '2025-07-24 10:23:17', 'R-189', 'Carry party spring charge just strong nor.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (56, 6, '2025-09-06 17:13:12', 'R-144', 'Case receive security ever imagine surface.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (61, 14, '2025-05-14 02:21:00', 'R-358', 'Better vote action deep again laugh receive.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (52, 7, '2025-06-25 06:22:57', 'R-137', 'Find seven night song.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (60, 15, '2025-07-29 02:13:40', 'R-273', 'Staff enter next always that.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (37, 9, '2025-05-27 11:49:15', 'R-122', 'Produce year determine reason audience TV.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (93, 1, '2025-08-05 10:18:16', 'R-246', 'Among himself other eight.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (7, 14, '2025-06-18 00:45:09', 'R-519', 'Tend population eat give property.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (75, 1, '2025-12-06 05:31:40', 'R-305', 'East wear long build.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (92, 19, '2026-01-05 09:03:13', 'R-162', 'Age check own skill wall investment.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (76, 15, '2025-03-23 02:46:10', 'R-174', 'North clearly could win.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (94, 9, '2025-04-20 22:12:39', 'R-483', 'Rise buy war lose commercial.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (80, 16, '2025-12-26 05:32:46', 'R-232', 'Need main no body not.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (53, 6, '2025-01-06 09:20:47', 'R-491', 'Control up manage enough particularly hour.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (39, 17, '2025-02-13 05:57:11', 'R-289', 'Get let guess speak guess.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (8, 19, '2025-09-21 21:53:48', 'R-445', 'Later wind too approach.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (59, 14, '2025-09-21 11:44:05', 'R-515', 'Side order fast offer heavy focus letter money.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (14, 17, '2025-03-15 11:08:37', 'R-328', 'All despite chair decide husband compare front focus.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (1, 13, '2025-05-11 17:06:33', 'R-217', 'Film plant fear man.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (59, 9, '2025-06-11 06:50:59', 'R-584', 'Painting they total enough.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (4, 5, '2025-06-01 05:24:31', 'R-187', 'Happen something down style.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (55, 9, '2025-03-28 05:55:55', 'R-550', 'Require consider treatment.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (59, 5, '2025-11-10 10:00:24', 'R-199', 'Show final common among recently.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (13, 8, '2025-12-26 09:13:04', 'R-500', 'Democrat three political well.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (64, 14, '2025-05-31 01:16:42', 'R-551', 'Interest manage for before.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (82, 7, '2025-01-08 01:14:00', 'R-390', 'Method grow check act.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (18, 13, '2025-11-04 06:43:11', 'R-377', 'Think method necessary every win.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (49, 11, '2025-01-17 18:36:34', 'R-521', 'Effect stay tend address.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (33, 2, '2025-06-18 18:37:26', 'R-432', 'For look second direction him teacher owner instead.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (18, 3, '2025-04-20 23:31:33', 'R-268', 'Pm fish final above.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (70, 13, '2026-01-09 23:04:53', 'R-570', 'Claim happen every.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (76, 15, '2025-08-27 10:53:31', 'R-417', 'Drive understand like add prove join.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (55, 6, '2026-02-01 05:00:29', 'R-379', 'After city sound expert impact.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (100, 16, '2025-09-22 21:03:08', 'R-474', 'Argue however dinner language.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (32, 6, '2025-11-04 16:44:58', 'R-351', 'Half sister little piece deal film level.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (99, 12, '2025-12-01 16:00:24', 'R-212', 'Single half down field little sure.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (40, 6, '2025-06-22 18:11:50', 'R-253', 'Threat policy might thank purpose particular.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (51, 7, '2025-02-07 07:51:59', 'R-530', 'Model suddenly inside walk.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (33, 19, '2025-10-21 14:38:50', 'R-455', 'Interest song its culture per.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (88, 18, '2025-03-16 14:29:39', 'R-146', 'Blood performance movement.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (99, 5, '2025-04-06 17:55:45', 'R-261', 'Forget significant foot election remain girl.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (89, 15, '2025-12-21 00:50:21', 'R-131', 'Road process find protect summer environment very.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (70, 19, '2025-08-03 01:27:59', 'R-232', 'Pass treatment first firm.', 'Completed');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (41, 3, '2025-02-18 13:53:29', 'R-434', 'Animal finally phone its memory quality after.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (4, 7, '2025-09-25 23:45:57', 'R-379', 'Set continue story.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (61, 20, '2025-07-05 21:20:01', 'R-353', 'You rock TV claim part sister.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (32, 9, '2025-09-09 01:17:16', 'R-347', 'Maybe still until scene example I.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (28, 11, '2025-09-12 17:43:14', 'R-134', 'Various head four seat.', 'Cancelled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (31, 5, '2026-01-28 20:26:35', 'R-543', 'Style join change hope nature.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (56, 5, '2025-09-01 01:04:44', 'R-568', 'War father amount rise may free.', 'Scheduled');
INSERT INTO appointments (patient_id, doctor_id, appointment_date, room_number, reason_for_visit, status) VALUES (3, 5, '2025-08-15 13:33:03', 'R-534', 'Prevent else world upon do daughter TV.', 'Cancelled');

-- 3. MEDICAL RECORDS 
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (88, 7, 'Hypertension', 'Among six rock old nearly red community.', '2025-05-16');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (50, 19, 'Fracture', 'Story able record least reach task consider beautiful technology power my.', '2025-04-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (27, 18, 'Pneumonia', 'Hand section research thank girl soon.', '2025-07-24');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (31, 4, 'Bronchitis', 'Start everyone book police true final.', '2025-08-07');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (77, 20, 'Covid-19', 'Often bank peace size final activity fund indeed own condition any three.', '2025-08-05');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (69, 11, 'Anemia', 'Investment sister because range student how I two.', '2025-03-04');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (67, 20, 'Gastritis', 'Player many matter police often prove.', '2025-04-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (61, 5, 'Asthma', 'Serve knowledge effect civil send TV them smile while win.', '2025-07-30');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (96, 12, 'Asthma', 'Road ball all body personal we listen trip.', '2025-03-20');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (19, 15, 'Anemia', 'Receive police career finally response more reflect me step operation offer street task.', '2025-09-11');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (72, 16, 'Covid-19', 'Point the morning staff group instead race treat surface theory positive trip.', '2025-04-01');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (32, 5, 'Asthma', 'Soldier behind sense one say go increase.', '2025-01-09');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (88, 17, 'Arthritis', 'Collection total similar measure both reveal hair main people rich.', '2025-08-27');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (38, 1, 'Migraine', 'Media particularly top low customer field million opportunity water parent end growth.', '2025-01-28');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (90, 2, 'Hypertension', 'My none particularly a free doctor deal business now cold.', '2025-10-18');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (87, 8, 'Hypertension', 'Old system trip boy spend management yet point.', '2025-05-05');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (79, 10, 'Gastritis', 'Take exactly compare parent center term at expert physical sea.', '2025-05-25');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (36, 5, 'Fracture', 'Son movie throughout fish bed professor beat card.', '2025-01-14');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (86, 17, 'Gastritis', 'Standard matter security worry way mind summer certainly man local least office very.', '2025-05-13');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (19, 10, 'Covid-19', 'If stop might nation toward a kid soon mind garden.', '2025-02-13');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (35, 17, 'Gastritis', 'Consider account free owner situation actually alone loss blood available very season story.', '2025-07-24');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (67, 4, 'Migraine', 'Career design company produce pick cultural game left whose interest strong.', '2025-09-18');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (99, 17, 'Pneumonia', 'Know from guess government significant happy understand town very listen contain arrive field.', '2025-04-06');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (38, 13, 'Covid-19', 'Ball morning financial from job tonight.', '2025-12-07');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (46, 9, 'Arthritis', 'Cold fast over realize owner enough question.', '2025-07-08');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (80, 6, 'Pneumonia', 'Leg truth establish take read rather.', '2025-05-19');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (99, 7, 'Diabetes Type 2', 'Financial real not audience career recently age.', '2025-07-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (75, 1, 'Gastritis', 'Send just probably push rather detail when.', '2025-10-23');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (73, 11, 'Covid-19', 'Accept back long thus glass a soon clear dog sign onto.', '2025-12-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (84, 20, 'Anemia', 'Against phone six notice sister record money tend reach education notice through position.', '2025-12-11');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (74, 1, 'Bronchitis', 'Benefit director go organization data become responsibility life cost will.', '2025-01-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (11, 6, 'Viral Fever', 'Too score level dream pretty claim week move hope lead.', '2025-03-06');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (84, 2, 'Anemia', 'Necessary speak ground oil human not sign.', '2025-03-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (33, 5, 'Migraine', 'Expert great such radio watch doctor win expect picture long agent share.', '2025-01-19');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (82, 15, 'Asthma', 'Happy trip type over speak behavior.', '2025-06-08');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (61, 20, 'Hypertension', 'Work tree option job how early possible open knowledge sing world.', '2025-06-28');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (67, 5, 'Arthritis', 'Glass summer we mother tonight floor evening short score.', '2025-12-31');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (3, 18, 'Bronchitis', 'Letter true answer whatever defense raise type thank office several involve pressure computer.', '2025-02-27');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (68, 3, 'Covid-19', 'Change girl reality little someone whose production true through every know charge.', '2025-08-19');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (54, 7, 'Migraine', 'Cover vote this answer realize black impact gas deep expert.', '2025-03-12');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (81, 7, 'Fracture', 'White institution century character better upon senior study particular another child check.', '2025-01-21');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (41, 6, 'Covid-19', 'Politics party lay go personal character on second media force protect.', '2025-04-28');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (25, 18, 'Diabetes Type 2', 'Few forget first investment baby movement through.', '2025-06-13');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (90, 15, 'Gastritis', 'Up collection paper half fish college writer could answer water employee together network.', '2025-06-15');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (82, 7, 'Arthritis', 'World beat lawyer worry mention hour rock book us mission bag.', '2025-10-13');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (67, 15, 'Viral Fever', 'Better population response mission record attention toward story administration society center member land.', '2025-07-11');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (61, 3, 'Asthma', 'Quite down small debate about environment your enough commercial race you you would.', '2025-03-19');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (40, 16, 'Migraine', 'Single approach daughter task cut at likely tend threat citizen west.', '2025-04-20');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (100, 20, 'Arthritis', 'Wait board next whose star hospital.', '2025-01-30');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (80, 20, 'Covid-19', 'Challenge race customer receive offer position kind specific.', '2025-06-24');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (19, 15, 'Asthma', 'Happen way culture become practice strong person foreign message.', '2025-12-22');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (73, 15, 'Bronchitis', 'Fly true pay draw college owner play of.', '2025-04-11');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (15, 4, 'Viral Fever', 'Industry recognize later authority produce cover today growth more serious number.', '2025-02-25');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (82, 6, 'Diabetes Type 2', 'Million wish likely be throughout political follow.', '2026-01-02');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (33, 13, 'Anemia', 'Degree reflect feeling degree Democrat officer seem free type.', '2025-08-04');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (59, 19, 'Diabetes Type 2', 'Star benefit deal economic success painting there film significant trade society event.', '2025-06-14');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (75, 20, 'Diabetes Type 2', 'Get factor no behavior another size support three.', '2025-10-20');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (20, 14, 'Anemia', 'Ten collection stop task ok color feeling star fast tend sometimes.', '2025-11-14');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (97, 20, 'Diabetes Type 2', 'Page must expert ahead make argue garden project show over born.', '2025-03-01');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (94, 11, 'Bronchitis', 'Next choice really clearly into heavy rather expect.', '2025-02-24');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (53, 9, 'Gastritis', 'Across executive economy candidate water ready born inside worker character.', '2025-12-09');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (19, 5, 'Bronchitis', 'Themselves fund day step several cost run my.', '2025-02-01');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (13, 5, 'Gastritis', 'Some wind more add difficult church meet cup positive skin really early more.', '2025-11-13');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (3, 18, 'Fracture', 'Thus bar various dark check smile but special customer today campaign.', '2025-05-03');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (69, 18, 'Hypertension', 'Live beyond pass one speech theory change along investment.', '2025-03-21');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (98, 14, 'Asthma', 'Better coach mouth data where get office food manager great edge day someone.', '2025-10-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (13, 14, 'Covid-19', 'Whether purpose response arrive would season red car.', '2025-08-04');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (50, 1, 'Viral Fever', 'Include people hospital their stock tough north strong leave.', '2025-01-16');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (50, 2, 'Hypertension', 'Stop interview Republican be exactly people economic page perform hand put hit have.', '2025-03-31');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (55, 6, 'Viral Fever', 'Movie southern purpose large among various fall anyone cup.', '2025-01-05');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (33, 17, 'Covid-19', 'These else forward body senior market stage sometimes almost discover decade energy.', '2025-12-09');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (66, 1, 'Anemia', 'Sort chair her hour must show production interview rate.', '2025-11-26');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (67, 17, 'Fracture', 'Allow seem case around on friend.', '2025-07-04');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (18, 6, 'Fracture', 'Religious necessary believe consider common stock.', '2025-03-31');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (9, 17, 'Migraine', 'Book wish card for opportunity mean administration family property forward apply save before.', '2025-03-23');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (2, 18, 'Viral Fever', 'Science appear course page event ready television fill.', '2025-07-22');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (63, 11, 'Fracture', 'Size six thus his dream hope pretty notice high.', '2025-04-08');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (60, 14, 'Arthritis', 'Media economic of because treat major for lead wife piece drive son.', '2025-01-22');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (17, 18, 'Bronchitis', 'Study produce budget I oil impact American edge art image majority brother.', '2025-05-31');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (68, 3, 'Gastritis', 'Bed without road will sure reach.', '2025-08-31');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (80, 13, 'Diabetes Type 2', 'Coach or idea star need put realize great.', '2025-03-01');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (58, 13, 'Migraine', 'Read begin its nice rich recently kitchen sell many.', '2025-02-17');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (51, 12, 'Fracture', 'Century by rate administration different wrong suddenly me because hear deep eight meeting.', '2025-12-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (56, 2, 'Fracture', 'Buy play card challenge might source.', '2025-04-19');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (10, 13, 'Asthma', 'Garden born responsibility sure finally near need system with type somebody economic movement.', '2025-03-19');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (43, 16, 'Gastritis', 'Take race stop option still or thought choice operation small by when.', '2025-12-23');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (88, 9, 'Viral Fever', 'Management position general hold weight shoulder particular young career teach occur area certain.', '2025-08-29');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (95, 5, 'Fracture', 'Down wish discussion total player newspaper run near energy explain rule.', '2025-02-23');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (56, 3, 'Migraine', 'Assume cell education expert by if artist artist before father author point name.', '2025-11-25');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (29, 9, 'Bronchitis', 'Already plant care within class down.', '2025-03-16');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (29, 16, 'Hypertension', 'Actually always again mission various challenge fish main next visit exist goal real.', '2025-05-28');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (37, 5, 'Hypertension', 'Fish nearly current generation work believe day.', '2025-09-02');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (86, 1, 'Covid-19', 'Political experience fill mother modern put source it public.', '2025-04-16');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (33, 20, 'Anemia', 'Would everything discussion ask southern action both material give or book scene.', '2025-07-29');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (52, 11, 'Pneumonia', 'Simply city community remain picture thank.', '2025-10-11');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (21, 19, 'Covid-19', 'Find particularly partner when without message laugh price member knowledge.', '2025-03-17');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (43, 17, 'Anemia', 'Just eat she break true policy trouble protect.', '2025-08-09');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (95, 7, 'Diabetes Type 2', 'Enough step improve edge push heavy pick rich southern whatever.', '2025-07-17');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (78, 13, 'Hypertension', 'Term painting attack research individual method senior true protect perhaps young administration response.', '2025-02-10');
INSERT INTO medical_records (patient_id, doctor_id, diagnosis, treatment_plan, record_date) VALUES (23, 18, 'Migraine', 'New eight hair street foot top pick total place particular need trouble.', '2025-01-06');

-- 4. ALLERGIES 
INSERT INTO allergies (patient_id, allergen, severity) VALUES (65, 'Latex', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (25, 'Peanuts', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (13, 'Latex', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (63, 'Dust', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (28, 'Pollen', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (76, 'Soy', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (27, 'Pollen', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (96, 'Shellfish', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (11, 'Milk', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (47, 'Dust', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (15, 'Pollen', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (23, 'Bee Stings', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (19, 'Penicillin', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (61, 'Dust', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (5, 'Penicillin', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (69, 'Pollen', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (89, 'Pollen', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (20, 'Dust', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (52, 'Soy', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (69, 'Latex', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (35, 'Milk', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (29, 'Shellfish', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (9, 'Soy', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (58, 'Peanuts', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (1, 'Shellfish', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (56, 'Penicillin', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (84, 'Pollen', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (42, 'Shellfish', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (49, 'Peanuts', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (10, 'Penicillin', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (52, 'Latex', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (92, 'Soy', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (69, 'Milk', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (42, 'Milk', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (99, 'Eggs', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (49, 'Penicillin', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (67, 'Penicillin', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (29, 'Peanuts', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (92, 'Peanuts', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (28, 'Latex', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (5, 'Penicillin', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (58, 'Milk', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (40, 'Milk', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (7, 'Pollen', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (43, 'Bee Stings', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (55, 'Pollen', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (5, 'Dust', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (100, 'Pollen', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (9, 'Soy', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (92, 'Bee Stings', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (1, 'Soy', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (83, 'Eggs', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (51, 'Shellfish', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (42, 'Bee Stings', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (21, 'Milk', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (37, 'Bee Stings', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (89, 'Bee Stings', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (51, 'Latex', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (19, 'Penicillin', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (32, 'Penicillin', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (19, 'Penicillin', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (65, 'Latex', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (27, 'Pollen', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (35, 'Soy', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (87, 'Latex', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (73, 'Bee Stings', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (72, 'Pollen', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (14, 'Pollen', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (30, 'Latex', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (17, 'Dust', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (86, 'Bee Stings', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (42, 'Shellfish', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (63, 'Bee Stings', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (50, 'Milk', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (89, 'Eggs', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (23, 'Milk', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (64, 'Pollen', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (82, 'Pollen', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (37, 'Pollen', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (100, 'Bee Stings', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (54, 'Shellfish', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (55, 'Dust', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (4, 'Pollen', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (91, 'Dust', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (43, 'Peanuts', 'Moderate');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (66, 'Pollen', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (100, 'Shellfish', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (15, 'Latex', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (16, 'Penicillin', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (73, 'Soy', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (50, 'Bee Stings', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (96, 'Shellfish', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (40, 'Dust', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (65, 'Penicillin', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (22, 'Peanuts', 'Severe');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (50, 'Peanuts', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (57, 'Bee Stings', 'Mild');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (17, 'Shellfish', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (54, 'Eggs', 'Life-Threatening');
INSERT INTO allergies (patient_id, allergen, severity) VALUES (47, 'Penicillin', 'Life-Threatening');

-- 5. INVOICES 
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (34, 8811.4, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (33, 8475.08, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (53, 8895.71, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (33, 10594.3, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (92, 14527.13, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (18, 17000.79, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (98, 11747.46, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (96, 8477.0, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (52, 14819.09, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (31, 9088.09, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (67, 9059.31, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (33, 15536.46, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (84, 9314.87, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (100, 3557.67, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (91, 4973.93, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (89, 19643.78, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (24, 1316.31, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (14, 9576.95, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (58, 17279.13, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (30, 2723.03, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (93, 11581.85, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (71, 13547.6, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (12, 5452.44, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (26, 9377.61, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (26, 15700.34, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (95, 1904.19, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (88, 18466.58, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (99, 17544.23, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (3, 8420.63, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (82, 8926.7, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (45, 18449.46, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (1, 11878.89, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (42, 5384.35, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (99, 2471.33, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (70, 9433.56, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (40, 1854.26, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (2, 10711.26, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (50, 16552.44, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (85, 18490.81, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (94, 1228.99, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (68, 6036.17, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (52, 12777.56, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (9, 3801.01, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (18, 8878.66, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (72, 6338.61, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (36, 9819.22, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (63, 2326.26, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (54, 17760.86, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (54, 2873.37, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (99, 1256.75, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (99, 3505.18, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (24, 4872.91, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (48, 3364.78, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (58, 3484.62, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (78, 257.51, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (55, 2494.56, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (71, 7457.47, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (58, 1928.87, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (3, 7760.37, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (30, 16064.26, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (33, 8658.29, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (20, 12846.37, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (98, 8311.24, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (23, 10205.94, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (70, 14525.08, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (88, 15172.57, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (36, 5855.9, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (60, 14933.87, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (32, 10045.21, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (99, 14922.68, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (11, 119.01, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (34, 7705.72, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (71, 4901.49, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (26, 12875.73, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (1, 15888.84, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (18, 13881.11, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (81, 14882.3, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (11, 3755.35, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (74, 5519.43, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (51, 11014.08, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (8, 3569.67, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (39, 5990.43, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (70, 18919.58, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (95, 14032.04, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (2, 11136.79, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (58, 4916.57, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (97, 9828.89, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (2, 8971.72, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (62, 3958.77, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (34, 14503.85, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (1, 8861.6, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (92, 15636.27, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (98, 4388.15, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (41, 16140.28, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (57, 7714.02, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (51, 6581.5, 'Unpaid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (59, 19616.01, 'Pending', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (17, 2115.51, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (100, 16324.34, 'Paid', '2026-01-03');
INSERT INTO invoices (patient_id, amount, status, issue_date) VALUES (91, 13416.32, 'Pending', '2026-01-03');

COMMIT;
